/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://e72dhdpxujh47dqxfvbnaubvye.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-nciab5da5vcmdg356ntt7rjyl4",
    "aws_cognito_identity_pool_id": "us-east-1:12827c14-a788-4b65-8e7c-d138adbf4646",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ljY80W1CJ",
    "aws_user_pools_web_client_id": "409e2o2e5r1dt29l79nh42ubtt",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 7,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "cornell-wushu-storage-edceb0fc180126-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
